### ISSUE TITLE
Azure pipelines support

### ISSUE THREAD

**Issue by Acelator** [JasonEtco/ci-reporter#58] opened 2019-01-30 19:29 UTC
Please add support for Azure pipelines

**Comment by JasonEtco** [comment] 2019-04-17 13:57
This'd be great to have - would you be up for opening a PR?

**Comment by nomego** [comment] 2019-07-02 10:54
Duplicate of #56 ?
Also, how would one go about adding/debugging a provider, is there a guide @JasonEtco ?

**Closed as completed** 2021-07-24 22:32 UTC
Labels: help wanted, new provider
